version: '3'

services:
  env_checker:
    build: ./app
    volumes:
      - /Users/antonshipulin/LOCAL/PyCharmProjects/EnvChecker/app:/usr/src/app
    ports:
      - 5001:80

  site:
    image: 38128dfb8fb2
    volumes:
      - /Users/antonshipulin/LOCAL/PyCharmProjects/EnvChecker/site:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - env_checker
